net:
  name: unet_water
  checkpoint: ~
  params:
    in_size: [10, 100, 100] 
    in_channels: 1
    out_size: [10, 100, 100]
    out_channels: 1 
    model_channels: 32 
    embedding_input: 0 # 0 for bulk water # 1 for cluster water
    embedding_channels: 128
    num_res_blocks: [1, 1] 
    attention_resolutions: [] 
    dropout: 0.0
    channel_mult: [1, 2, 3, 4] 
    out_mult: 1
    z_down: [1, 2, 4]
    conv_resample: True 

disc:
  name: n_layer_disc
  checkpoint: ~
  params:
    in_channels: 1
    model_channels: 32
    channels_mult: [8, 4, 2, 1]
    z_down: []
    norm: batch
