net: unet_water
checkpoint: /Users/supercgor/Documents/data/unetv3/unetv3_CP01_L0.0771.pkl
params:
  in_size: [10, 100, 100] 
  in_channels: 1
  out_size: [3, 25, 25]
  out_channels: 10 
  model_channels: 32 
  embedding_input: 2 # 0 for bulk water # 1 for cluster water
  embedding_channels: 128
  num_res_blocks: [3, 3] 
  attention_resolutions: [4, 8, 16] 
  dropout: 0.1 
  channel_mult: [1, 2, 3, 4, 8] 
  out_mult: 4
  z_down: [1, 2, 4]
  conv_resample: True 
  num_heads: 8 