net: unet_water
checkpoint: ~
params:
  in_size: [10, 100, 100] 
  in_channels: 1
  out_size: [3, 25, 25]
  out_channels: 10 
  model_channels: 32 
  embedding_input: 2 # 0 for bulk water # 1 for cluster water
  embedding_channels: 128
  num_res_blocks: [2, 2] 
  attention_resolutions: [0] 
  dropout: 0.1 
  channel_mult: [1, 2, 3, 4, 4] 
  out_mult: 4
  z_down: [1, 2, 4]
  conv_resample: True 
  num_heads: 8 