net: vae_v3
checkpoint: ~
params:
  in_size: [4, 25, 25] 
  in_channels: 4
  out_size: [16, 25, 25]
  out_channels: [1, 3, 6]
  out_conv_blocks: 2
  model_channels: 32
  embedding_input: 0
  embedding_channels: 0
  latent_channels: 512
  num_res_blocks: [2, 2]
  attention_resolutions: [4, 8, 16]
  dropout: 0
  channel_mult: [1, 2, 4, 6, 8]
  z_down: [4, 8]
  z_up: [1, 2, 4, 8]
  conv_resample: True
                  