net: ConditioalVAE3
checkpoint: ~
params:
  in_channel: 4
  model_channel: 16
  out_channel: 4
  latent_channel: 8
  dropout: 0

losses:
  conf_weight: 1.0
  offset_weight: 0.25
  vae_weight: 1.0
  pos_weight: 5.0

