test_path: ${data.test_path}
checkpoint: ${model.checkpoint}
label: false
save_pred: false
pred_loop: 3
transform: false
output: null
model:
  net: VAELatEmb
  max_save: 10
  checkpoint: null
  params:
    in_size: ${data.image_size}
    in_channels: 10
    out_size:
    - 4
    - 25
    - 25
    out_channels: 10
    model_channels: 32
    embedding_input: 1
    latent_channels: 256
    num_res_blocks:
    - 2
    - 2
    dropout: 0.0
    channel_mult:
    - 1
    - 2
    - 4
    - 8
    z_down:
    - 2
    - 8
    z_up:
    - 2
    - 8
    conv_resample: true
setting:
  epoch: 5
  batch_size: 1
  num_workers: 0
  pin_memory: true
  log_every: 4
data:
  train_path: /Users/supercgor/Documents/data/ice_8_4A/ice_8_4A_small_train.hdf5
  test_path: /Users/supercgor/Documents/data/ice_8_4A/ice_8_4A_small_test.hdf5
  valid_path: null
  image_size:
  - 4
  - 25
  - 25
  real_size:
  - 25.0
  - 25.0
  - 4.0
  ion_type:
  - O
  - H
  format: CZXY
  domain_adapt: false
  split:
  - 0.0
  - 4.0
  nms: true
criterion:
  lr: 0.0001
  weight_decay: 0.005
  clip_grad: 3.0
  pos_weight: 10
  cond_weight: 1.0
  xyz_weight: 2.0
  rot_weight: 0.25
  vae_weight: 0.01
  schedular:
    name: StepLR
    params:
      step_size: 2
      gamma: 0.5
