defaults:
  - _self_
  - model: vae_a0
  - setting: test
  - dataset: vae_local
  - criterion: vae

test_path: ${data.test_path}
checkpoint: ${model.checkpoint}
label: False
save_pred: False
pred_loop: 3
transform: False
output: ~
