defaults:
  - _self_
  - model: vae_v5
  - setting: default
  - dataset: vae_wm
  - criterion: vae

test_path: ${dataset.test_path}
checkpoint: ${model.checkpoint}
label: False
save_pred: False
pred_loop: 3
transform: False
output: ~
