lr: 1.0e-4
weight_decay: 5.0e-3
clip_grad: 5.0
pos_weight: [0.1, 1.0, 2.0] # None O H
cond_weight: 1.0
xy_weight: 0.5
z_weight: 0.5

schedular:
  name: StepLR
  params:
    step_size: 2
    gamma: 0.5